# Generated by Django 4.2.11 on 2024-05-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=80)),
                ('pendapatan_per_bulan', models.IntegerField()),
                ('pendapatan_lain_lain', models.IntegerField()),
                ('jumlah_anak', models.IntegerField()),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='InternalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('project_type', models.CharField(max_length=16)),
                ('project_location', models.CharField(max_length=80)),
                ('project_description', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='down_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='lama_cicil',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='project_location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='sales',
            name='project_manager_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sales',
            name='project_type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.CreateModel(
            name='SalesPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('jumlah_cicil', models.IntegerField(default=0)),
                ('tahun_cicil', models.IntegerField(default=0)),
                ('bulan_cicil', models.IntegerField(default=0)),
                ('sales_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.contact')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.project')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.sales')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.project'),
        ),
        migrations.AddField(
            model_name='sales',
            name='contacts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.contact'),
        ),
        migrations.AddField(
            model_name='sales',
            name='project_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.internalusers'),
        ),
        migrations.AddField(
            model_name='sales',
            name='projects',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.project'),
        ),
    ]
