# Generated by Django 4.2.11 on 2024-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0002_contact_internalusers_project_sales_down_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status_pernikahan',
            field=models.CharField(choices=[('sm', 'Sudah Menikah'), ('bm', 'Belum Menikah'), ('cn', 'Cerai Nikah'), ('cm', 'Cerai Mati')], default='bm', max_length=2),
        ),
    ]
