# Generated by Django 4.2.11 on 2024-05-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0003_contact_status_pernikahan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalusers',
            name='phone',
        ),
    ]
