# Generated by Django 4.2.11 on 2024-05-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0004_remove_internalusers_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='projects',
        ),
    ]
