# Generated by Django 4.2.11 on 2024-05-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0005_remove_contact_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.internalusers'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager_email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.DeleteModel(
            name='Project_Tenants',
        ),
    ]
