# Generated by Django 4.2.11 on 2024-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0006_project_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_total',
            field=models.IntegerField(default=0),
        ),
    ]
