# Generated by Django 4.2.11 on 2024-05-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0007_sales_sales_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='project_manager_phone',
            new_name='project_manager_email',
        ),
    ]
