# Generated by Django 4.2.11 on 2024-05-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0008_rename_project_manager_phone_sales_project_manager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='project_manager_email',
            field=models.CharField(default='', max_length=80),
        ),
    ]
