# Generated by Django 4.2.11 on 2024-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0009_alter_sales_project_manager_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespaymentdetails',
            name='description',
            field=models.CharField(default='', max_length=160),
        ),
    ]
