# Generated by Django 4.2.11 on 2024-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0010_salespaymentdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespaymentdetails',
            name='bulan_cicil',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='salespaymentdetails',
            name='tahun_cicil',
            field=models.CharField(default='', max_length=2),
        ),
    ]
