# Generated by Django 4.2.11 on 2024-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0011_alter_salespaymentdetails_bulan_cicil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespaymentdetails',
            name='bulan_cicil',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='salespaymentdetails',
            name='tahun_cicil',
            field=models.CharField(default='', max_length=16),
        ),
    ]
