# Generated by Django 4.2.11 on 2024-06-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0012_alter_salespaymentdetails_bulan_cicil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('project_manager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.project')),
            ],
        ),
    ]
