# Generated by Django 4.2.11 on 2024-06-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0013_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='project_manager',
            new_name='project',
        ),
    ]
