# Generated by Django 4.2.11 on 2024-06-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0015_remove_project_project_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kel4PSIA_web.cluster'),
        ),
    ]
