# Generated by Django 4.2.11 on 2024-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kel4PSIA_web', '0016_alter_sales_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
